# Author:
# Zhibiao Xie 980357
# Jingda Kang 1276802
# Haoxian Cai 1074429
# Zihan Xu 1198129
# Keyi Zhang 1217718
# Last updated: 2022-5-17

# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: group32_key
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: group32-vol-1-1
    vol_size: 10
  - vol_name: group32-vol-1-2
    vol_size: 10
  - vol_name: group32-vol-2-1
    vol_size: 10
  - vol_name: group32-vol-2-2
    vol_size: 10
  - vol_name: group32-vol-3-1
    vol_size: 10
  - vol_name: group32-vol-3-2
    vol_size: 10
  - vol_name: group32-vol-4-1
    vol_size: 10
  - vol_name: group32-vol-4-2
    vol_size: 10

# Security group
security_groups:
  - name: instance_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: instance_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: instance_couchdb_http
    description: "Security group for couchdb cluster setup"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: instance_couchdb_epmd
    description: "Erlang port mapper daemon (epmd)"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: instance_couchdb_interconnection
    description: "Communication with other CouchDB nodes in the cluster"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: group32-1
    volumes: ['group32-vol-1-1', 'group32-vol-1-2']
  - name: group32-2
    volumes: ['group32-vol-2-1', 'group32-vol-2-2']
  - name: group32-3
    volumes: ['group32-vol-3-1', 'group32-vol-3-2']
  - name: group32-4
    volumes: ['group32-vol-4-1', 'group32-vol-4-2']

# Couchdb user and password
username: admin
password: admin
